
data:
  fx_data_path: "data/FX"
  fred_data_path: "data/FRED"
  output_path: "output"
  pairs:
    - AUDNZD
    - EURUSD
    - GBPUSD

model:
  pricing_model: "VGVV"
  calibration_window: 60
  calibration_frequency: 20

strategy:
  initial_capital: 1000000
  position_sizing_method: "kelly"
  max_position_size: 0.02
  vol_threshold: 0.005
  max_positions: 50
  target_delta_neutral: true

risk:
  stop_loss: 0.02
  take_profit: 0.05
  max_drawdown: 0.10
  max_vega: 50000

execution:
  bid_ask_spread: 0.001
  commission: 0.0001

backtest:
  start_date: "2006-01-01"
  end_date: "2023-12-31"
  rebalance_frequency: "daily"
  save_results: true
  generate_report: true

log_level: "INFO"
parallel_processing: true
num_workers: 4
