[data]
fxo_path = "../data/input/fxo.parquet"
curve_path = "../data/output/curve.parquet"
date_col = "date"

[pairs]
universe = ["USDJPY","USDCAD","GBPNZD"]

[tenors]
list = ["1W","2W","3W","1M","2M","3M"]

[target_deltas]
abs = [0.05, 0.10, 0.25, 0.35, 0.45]

[models]
use = ["BLACK","GK","SABR","VGVV"]

[sabr]
beta = 1.0
calib_window_years = 3

[allocation]
lookback_years = 5
rebalance = "M"
methods = ["max_return","max_sharpe"]
drawdown_target = 0.10

[hedging]
delta_threshold = 0.04
spot_cost_pips_majors = 1.0
spot_cost_pips_crosses = 3.0

[costs]
option_trade_bps_atm = 15
option_trade_bps_wings = 30
min_tick_value = 0.0

[margin]
kappa = 0.10
floor = 0.01

[capital]
initial_aum = 1_000_000.0
max_utilization = 0.8

[reporting]
outdir = "../results"

[conventions]
day_count = 365.0
delta_convention = "forward"
